"""Initial schema

Revision ID: fab85f684593
Revises: 
Create Date: 2026-09-06 14:15:04.870781

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fab85f684593'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_line',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('matched_payout_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['matched_payout_id'], ['payout.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_line_run_id'), 'bank_line', ['run_id'], unique=False)
    op.create_table('close_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rules_enabled', sa.Boolean(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_close_run_period'), 'close_run', ['period'], unique=False)
    op.create_table('exception',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=4, scale=3), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('hypotheses', sa.JSON(), nullable=True),
    sa.Column('proposed_remedy', sa.JSON(), nullable=True),
    sa.Column('detected_by', sa.String(length=50), nullable=False),
    sa.Column('matched_rule_id', sa.String(length=36), nullable=True),
    sa.Column('ground_truth_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_run_id'), 'exception', ['run_id'], unique=False)
    op.create_table('gl_account',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('normal_side', sa.String(length=6), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('human_ruling',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.String(length=2000), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exception.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_ruling_exception_id'), 'human_ruling', ['exception_id'], unique=False)
    op.create_table('payout',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('gross', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('fees', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('net', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank_line_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['bank_line_id'], ['bank_line.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_payout_run_id'), 'payout', ['run_id'], unique=False)
    op.create_table('rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('predicate', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.String(length=2000), nullable=True),
    sa.Column('source_ruling_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_ruling_id'], ['human_ruling.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_at'), 'audit_event', ['at'], unique=False)
    op.create_index(op.f('ix_audit_event_run_id'), 'audit_event', ['run_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('tax', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('total', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_run_id'), 'invoice', ['run_id'], unique=False)
    op.create_table('journal_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_exception_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.ForeignKeyConstraint(['source_exception_id'], ['exception.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_run_id'), 'journal_entry', ['run_id'], unique=False)
    op.create_table('proof_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('obligation', sa.String(length=3), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('expected', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('actual', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('delta', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_result_run_id'), 'proof_result', ['run_id'], unique=False)
    op.create_table('settlement_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payout_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('amount_native', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('currency_native', sa.String(length=3), nullable=False),
    sa.Column('amount_payout', sa.NUMERIC(precision=18, scale=4), nullable=False),
    sa.Column('currency_payout', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.NUMERIC(precision=18, scale=8), nullable=True),
    sa.Column('fx_source', sa.String(length=50), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['close_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_event_payout_id'), 'settlement_event', ['payout_id'], unique=False)
    op.create_index(op.f('ix_settlement_event_run_id'), 'settlement_event', ['run_id'], unique=False)
    op.create_table('journal_line',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('account_code', sa.String(length=10), nullable=False),
    sa.Column('debit', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('credit', sa.NUMERIC(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settlement_event_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('(debit > 0 AND credit = 0) OR (debit = 0 AND credit > 0)'),
    sa.ForeignKeyConstraint(['account_code'], ['gl_account.code'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['settlement_event_id'], ['settlement_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_line_entry_id'), 'journal_line', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_line_entry_id'), table_name='journal_line')
    op.drop_table('journal_line')
    op.drop_index(op.f('ix_settlement_event_run_id'), table_name='settlement_event')
    op.drop_index(op.f('ix_settlement_event_payout_id'), table_name='settlement_event')
    op.drop_table('settlement_event')
    op.drop_index(op.f('ix_proof_result_run_id'), table_name='proof_result')
    op.drop_table('proof_result')
    op.drop_index(op.f('ix_journal_entry_run_id'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_invoice_run_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_audit_event_run_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_at'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('rule')
    op.drop_index(op.f('ix_payout_run_id'), table_name='payout')
    op.drop_table('payout')
    op.drop_index(op.f('ix_human_ruling_exception_id'), table_name='human_ruling')
    op.drop_table('human_ruling')
    op.drop_table('gl_account')
    op.drop_index(op.f('ix_exception_run_id'), table_name='exception')
    op.drop_table('exception')
    op.drop_index(op.f('ix_close_run_period'), table_name='close_run')
    op.drop_table('close_run')
    op.drop_index(op.f('ix_bank_line_run_id'), table_name='bank_line')
    op.drop_table('bank_line')
    # ### end Alembic commands ###
